services:
  postgres:
    image: postgres:latest
    container_name: postgres-db
    environment:
      - POSTGRES_DB=investments
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=sevenofdiamonds
    volumes:
      - postgres_data:/var/lib/postgresql/data 
      - ./db-scripts:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"
    networks:
      - app-network
    
  frontend:
    build:
      context: ./Frontend 
      dockerfile: Dockerfile
    ports:
      - "443:443"
    depends_on:
      - backend
    networks:
      - app-network

  backend:
    build: 
      context: ./Backend
      dockerfile: Dockerfile
    environment:   
      ASPNETCORE_ENVIRONMENT: "Production"
      TIINGO_API_KEY: "dummytext"

    ports:
      - "5000:5000"
    depends_on:
      - postgres
    networks:
      - app-network
  
  cronjob:
    build:
      context: ./CronJob 
      dockerfile: Dockerfile
    environment:
      - TIINGO_API_KEY=dummytext
    depends_on:
      - postgres 
    networks:
      - app-network


volumes:
  postgres_data:

networks:
  app-network:
    driver: bridge
